version: '3.7'

services:
  db:
    image: postgres
    container_name: postgres-container
    volumes:
    - type: volume
      source: db-data
      target: /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
    restart: always
    ports:
      - "5432:5432"
  api: 
    build: "."
    container_name: api-container
    ports: 
      - "8080:8080"
    depends_on:
      - db

volumes:
  db-data:
    driver: local