version: '3.7'

services:
  db:
    image: postgres
    container_name: postgres-container
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
    restart: always
    ports:
      - "5432:5432"
  api: 
    build: "."
    container_name: api-container
    ports:
      - "8080:8080"
    depends_on:
      - db
